<?php

require_once __DIR__ . '/../safemysql.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-04 at 07:42:48.
 */
class SafeMSyQLTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SafeMySQL
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->db = new SafeMSyQL(array(
        'user' => 'root',
        'pass' => 'SuperVGA256',
        'db' => 'test',
        'host' => '192.168.56.101',
        'charset' => 'utf8'
        ));
        
        $this->db->query('DROP TABLE IF EXISTS t1;');
        $this->db->query('CREATE TABLE t1 (id INT, value VARCHAR(25));');
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->db->query('DROP TABLE IF EXISTS t1;');
        unset($this->db);
    }

    /**
     * @covers SafeMySQL::query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
            $this->assertEquals(
                $this->io->getCldCntName(), 'straetus-dev'
        );
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::affectedRows
     * @todo   Implement testAffectedRows().
     */
    public function testAffectedRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::insertId
     * @todo   Implement testInsertId().
     */
    public function testInsertId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::numRows
     * @todo   Implement testNumRows().
     */
    public function testNumRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::free
     * @todo   Implement testFree().
     */
    public function testFree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getOne
     * @todo   Implement testGetOne().
     */
    public function testGetOne() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getRow
     * @todo   Implement testGetRow().
     */
    public function testGetRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getCol
     * @todo   Implement testGetCol().
     */
    public function testGetCol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getInd
     * @todo   Implement testGetInd().
     */
    public function testGetInd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getIndCol
     * @todo   Implement testGetIndCol().
     */
    public function testGetIndCol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::whiteList
     * @todo   Implement testWhiteList().
     */
    public function testWhiteList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::filterArray
     * @todo   Implement testFilterArray().
     */
    public function testFilterArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::lastQuery
     * @todo   Implement testLastQuery().
     */
    public function testLastQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SafeMySQL::getStats
     * @todo   Implement testGetStats().
     */
    public function testGetStats() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
